### PR TITLE
 fix file path as option & handle paths on windows

### LINKED ISSUE #5: log issues
First of all thanks for this great project. This makes testing with selenium in different browsers much easier :)

Unfortunately, I found a few issues with the `seleniumLogs` option:
1. it's not possible to specify a file path. Only directories are supported, otherwise the file will be created as directory if it doesn't exist yet (see [L61](https://github.com/webdriverio/wdio-selenium-standalone-service/blob/955480e369fc0608e23836648cb14a4657150b8d/lib/launcher.js#L61)).
2. seleniumLogs fails on windows caused by a wrong path separator check (see [L64](https://github.com/webdriverio/wdio-selenium-standalone-service/blob/955480e369fc0608e23836648cb14a4657150b8d/lib/launcher.js#L64))
3. it should handle absolute paths

I'm happy to submit a PR to fix these issues.

### PR DESCRIPTION
**Pull request by zinserjan**
Changes:
- detect if a file is provided to seleniumLogs, otherwise use default file
- fix path handling on windows
- replaced mkdirp with fs-extra.ensureFileSync

Fixes #5

@christian-bromann what's the best way to add additional specs to test the different kinds of path options? Defining different configs for each use case seems a bit complicated.

Maybe it makes sense to use plain mocha and refactor the log file path handling to it's own file.

### CODE REVIEW

**Comment by christian-bromann** [comment]
> Maybe it makes sense to use plain mocha and refactor the log file path handling to it's own file.

Yes, feel free to do this. The current test is just an integration tests but it definitely makes sense to have unit tests for some code paths.

**Comment by zinserjan** [comment]
I added some unit tests for this.

All issues are solved except the handling of absolute paths.  We should address this in another PR, cause it's a breaking change.

Currently the absolute path `/log/selenium-logs.txt` resolves to `process.cwd() + /log/selenium-logs.txt`. After the change it would just resolve to `/log/selenium-logs.txt`

**Comment by christian-bromann** [comment]
Nice job man! 🎉

**Comment by christian-bromann** [comment]
released with `v0.0.5`

**Pull request merged**
