### PR TITLE
Add npm run build to prepublish script

### PR DESCRIPTION
**Pull request by andriilazebnyi**
See https://github.com/webdriverio/wdio-selenium-standalone-service/issues/2#issuecomment-217272950

### CODE REVIEW

**Comment by christian-bromann** [comment]
@andriilazebnyi thanks for figuring out the problem. I would rather want to build the project in the prepublish hook

**Comment by christian-bromann** [comment]
If you want to build the project after install, you would need to install all devdependencies which would be a waste of resources

**Comment by andriilazebnyi** [comment]
@christian-bromann Understood. Should I create a new pull request? Or update existing one?

**Comment by christian-bromann** [comment]
no just commit on this one

**Comment by andriilazebnyi** [comment]
Done. However, build fails due to the following error:

> ERROR: Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:
> Error: no display specified

https://travis-ci.org/webdriverio/wdio-selenium-standalone-service/builds/128148647

**Comment by christian-bromann** [comment]
Thanks, yeah I need to fix that as well, isn't that important though

**Comment by christian-bromann** [comment]
Thanks!

**Comment by andriilazebnyi** [comment]
Great! Thank you!

**Comment by ManoranjanKanungo** [comment]
Hi,
Still I am seeing this error.

C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\webdriverio\build\lib\cli.js:431
            throw e;
            ^

**Error: Couldn't initialise launcher from service "selenium-standalone".**
C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\selenium-standalone\lib\install.js:443
    cb(new Error('Could not request headers from ' + url + ': ' + err))����v�W♫L5
                                                                       ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\selenium-standalone\index.js:2:12)
    at Module._compile (module.js:570:32)
    at Launcher.getLauncher (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\webdriverio\build\lib\launcher.js:731:35)
    at Launcher._callee$ (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\webdriverio\build\lib\launcher.js:233:49)
    at tryCatch (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\regenerator-runtime
\runtime.js:116:21)
    at step (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at Promise.F (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\core-js\library\modules\_export.js:35:28)
    at Launcher.<anonymous> (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at Launcher.run (C:\NPM_AUTOMATION\webdriverio-automation-framework-master\node_modules\webdriverio\build\lib\launcher.js:373:29)

*********
"scripts": {
    "postinstall": "selenium-standalone install",
     "build": "grunt build",
    "prepublish": "npm prune && npm run build",
    "test": "npm run single && npm run local && npm run parallel",
    "single": "./node_modules/.bin/wdio conf/single.conf.js",
    "parallel": "./node_modules/.bin/wdio conf/parallel.conf.js",
    "local": "./node_modules/.bin/wdio conf/local.conf.js",
    "multiple": "./node_modules/.bin/wdio conf/multiple.conf.js",
    "standalone": "./node_modules/.bin/wdio conf/standalone.conf.js"
  },

Anything am I missing ? it was working fine up to yesterday not very sure what happen :(.

**Comment by eelessam** [comment]
@ManoranjanKanungo Did you get anywhere with this? I'm having the same problem now

**Comment by eelessam** [comment]
I've just noticed that my npm install seems to be ending here with no error when it gets to installing fibre similar to here: https://github.com/webdriverio/wdio-cucumber-framework/issues/39. I then get the problem you're having when I try to run my tests.

**Pull request merged**
