### PR TITLE
Update selenium-standalone to 6.13 to have the 2.36 chromedriver fix

### PR DESCRIPTION
**Pull request by davidaubin19**
- See vvo/selenium-standalone@0e5e206 and webdriverio/webdriverio#2631 for details

## test run
screen shot 2018-03-09 at 2 11 50 pm
screen shot 2018-03-09 at 2 11 30 pm

### CODE REVIEW

**Comment by christian-bromann** [comment]
Happy to merge this once CLA is signed.

**Comment by davidaubin19** [comment]
@christian-bromann Done 👍  had wrong user.email git config! Thanks!

**Review by christian-bromann — APPROVED** [review]
Thanks!

**Comment by cris7ea** [comment]
Was this published to NPM?
I'm asking because I'm still getting `^6.5.0` in package.json of this project from NPM.

**Comment by christian-bromann** [comment]
My apology. I kept a package-lock in there which prevented NPM from downloading a newer version. That has been fixed in `v0.0.10`

**Pull request merged**
